import '../globals.css';
import type { Metadata } from 'next';
import { useLocale } from 'next-intl';
import { NextIntlClientProvider } from 'next-intl';
import Navbar from '@/components/Navbar';
import { Fira_Code } from 'next/font/google';
const fira = Fira_Code({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Ambrosialab',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();
  return (
    <html lang={locale}>
      <body className={fira.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
